spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scca?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 3571571
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db-name: adi-boot
  redis:
    host: localhost
    port: 6379
    password:
    database: 9
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.id.new_generator_mappings: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


